using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PathOfServant
{
    class ItemData
    {
        public static Dictionary<string, string> FillOutItemData()
        {
            Dictionary<string, string> result = new Dictionary<string, string>();
            result.Add("Crude Bow", "weapon2h");
            result.Add("Short Bow", "weapon2h");
            result.Add("Long Bow", "weapon2h");
            result.Add("Composite Bow", "weapon2h");
            result.Add("Recurve Bow", "weapon2h");
            result.Add("Bone Bow", "weapon2h");
            result.Add("Royal Bow", "weapon2h");
            result.Add("Death Bow", "weapon2h");
            result.Add("Grove Bow", "weapon2h");
            result.Add("Decurve Bow", "weapon2h");
            result.Add("Compound Bow", "weapon2h");
            result.Add("Sniper Bow", "weapon2h");
            result.Add("Ivory Bow", "weapon2h");
            result.Add("Highborn Bow", "weapon2h");
            result.Add("Decimation Bow", "weapon2h");
            result.Add("Thicket Bow", "weapon2h");
            result.Add("Citadel Bow", "weapon2h");
            result.Add("Ranger Bow", "weapon2h");
            result.Add("Maraketh Bow", "weapon2h");
            result.Add("Chimeric Bow", "weapon2h");
            result.Add("Imperial Bow", "weapon2h");
            result.Add("Armageddon Bow", "weapon2h");
            result.Add("Gnarled Branch", "weapon2h");
            result.Add("Primitive Staff", "weapon2h");
            result.Add("Long Staff", "weapon2h");
            result.Add("Iron Staff", "weapon2h");
            result.Add("Coiled Staff", "weapon2h");
            result.Add("Royal Staff", "weapon2h");
            result.Add("Vile Staff", "weapon2h");
            result.Add("Woodful Staff", "weapon2h");
            result.Add("Quarterstaff", "weapon2h");
            result.Add("Military Staff", "weapon2h");
            result.Add("Serpentine Staff", "weapon2h");
            result.Add("Highborn Staff", "weapon2h");
            result.Add("Foul Staff", "weapon2h");
            result.Add("Primordial Staff", "weapon2h");
            result.Add("Lathi", "weapon2h");
            result.Add("Ezoymte Staff", "weapon2h");
            result.Add("Maelström Staff", "weapon2h");
            result.Add("Maelstrom Staff", "weapon2h");
            result.Add("Imperial Staff", "weapon2h");
            result.Add("Damnation Staff", "weapon2h");
            result.Add("Stone Axe", "weapon2h");
            result.Add("Jade Chopper", "weapon2h");
            result.Add("Woodsplitter", "weapon2h");
            result.Add("Poleaxe", "weapon2h");
            result.Add("Double Axe", "weapon2h");
            result.Add("Gilded Axe", "weapon2h");
            result.Add("Shadow Axe", "weapon2h");
            result.Add("Jasper Chopper", "weapon2h");
            result.Add("Timber Axe", "weapon2h");
            result.Add("Headsman Axe", "weapon2h");
            result.Add("Labrys", "weapon2h");
            result.Add("Noble Axe", "weapon2h");
            result.Add("Abyssal Axe", "weapon2h");
            result.Add("Karui Chopper", "weapon2h");
            result.Add("Sundering Axe", "weapon2h");
            result.Add("Ezomyte Axe", "weapon2h");
            result.Add("Vaal Axe", "weapon2h");
            result.Add("Despot Axe", "weapon2h");
            result.Add("Void Axe", "weapon2h");
            result.Add("Driftwood Maul", "weapon2h");
            result.Add("Tribal Maul", "weapon2h");
            result.Add("Mallet", "weapon2h");
            result.Add("Sledgehammer", "weapon2h");
            result.Add("Spiked Maul", "weapon2h");
            result.Add("Brass Maul", "weapon2h");
            result.Add("Fright Maul", "weapon2h");
            result.Add("Totemic Maul", "weapon2h");
            result.Add("Great Mallet", "weapon2h");
            result.Add("Steelhead", "weapon2h");
            result.Add("Spiny Maul", "weapon2h");
            result.Add("Plated Maul", "weapon2h");
            result.Add("Dread Maul", "weapon2h");
            result.Add("Karui Maul", "weapon2h");
            result.Add("Colossus Mallet", "weapon2h");
            result.Add("Piledriver", "weapon2h");
            result.Add("Meatgrinder", "weapon2h");
            result.Add("Imperial Maul", "weapon2h");
            result.Add("Terror Maul", "weapon2h");
            result.Add("Corroded Blade", "weapon2h");
            result.Add("Long Sword", "weapon2h");
            result.Add("Bastard Sword", "weapon2h");
            result.Add("Two-Handed Sword", "weapon2h");
            result.Add("Etched Greatsword", "weapon2h");
            result.Add("Ornate Sword", "weapon2h");
            result.Add("Spectral Sword", "weapon2h");
            result.Add("Butcher Sword", "weapon2h");
            result.Add("Footman Sword", "weapon2h");
            result.Add("Highland Blade", "weapon2h");
            result.Add("Engraved Greatsword", "weapon2h");
            result.Add("Tiger Sword", "weapon2h");
            result.Add("Wraith Sword", "weapon2h");
            result.Add("Headman's Sword", "weapon2h");
            result.Add("Reaver Sword", "weapon2h");
            result.Add("Ezomyte Blade", "weapon2h");
            result.Add("Vaal Greatsword", "weapon2h");
            result.Add("Lion Sword", "weapon2h");
            result.Add("Infernal Sword", "weapon2h");
            result.Add("Nailed Fist", "weapon1h");
            result.Add("Sharktooth Claw", "weapon1h");
            result.Add("Awl", "weapon1h");
            result.Add("Cat's Paw", "weapon1h");
            result.Add("Blinder", "weapon1h");
            result.Add("Timeworn Claw", "weapon1h");
            result.Add("Sparkling Claw", "weapon1h");
            result.Add("Fright Claw", "weapon1h");
            result.Add("Thresher Claw", "weapon1h");
            result.Add("Gouger", "weapon1h");
            result.Add("Tiger's Paw", "weapon1h");
            result.Add("Gut Ripper", "weapon1h");
            result.Add("Prehistoric Claw", "weapon1h");
            result.Add("Noble Claw", "weapon1h");
            result.Add("Dread Claw", "weapon1h");
            result.Add("Great White Claw", "weapon1h");
            result.Add("Throat Stabber", "weapon1h");
            result.Add("Hellion's Paw", "weapon1h");
            result.Add("Eye Gouger", "weapon1h");
            result.Add("Vaal Claw", "weapon1h");
            result.Add("Imperial Claw", "weapon1h");
            result.Add("Terror Claw", "weapon1h");
            result.Add("Glass Shank", "weapon1h");
            result.Add("Skinning Knife", "weapon1h");
            result.Add("Carving Knife", "weapon1h");
            result.Add("Stiletto", "weapon1h");
            result.Add("Boot Knife", "weapon1h");
            result.Add("Copper Kris", "weapon1h");
            result.Add("Skean", "weapon1h");
            result.Add("Imp Dagger", "weapon1h");
            result.Add("Flaying Knife", "weapon1h");
            result.Add("Butcher Knife", "weapon1h");
            result.Add("Poinard", "weapon1h");
            result.Add("Boot Blade", "weapon1h");
            result.Add("Golden Kris", "weapon1h");
            result.Add("Royal Skean", "weapon1h");
            result.Add("Fiend Dagger", "weapon1h");
            result.Add("Gutting Knife", "weapon1h");
            result.Add("Slaughter Knife", "weapon1h");
            result.Add("Ambusher", "weapon1h");
            result.Add("Ezomyte Dagger", "weapon1h");
            result.Add("Platinum Kris", "weapon1h");
            result.Add("Imperial Skean", "weapon1h");
            result.Add("Demon Dagger", "weapon1h");
            result.Add("Rusted Hatchet", "weapon1h");
            result.Add("Jade Hatchet", "weapon1h");
            result.Add("Boarding Axe", "weapon1h");
            result.Add("Cleaver", "weapon1h");
            result.Add("Broad Axe", "weapon1h");
            result.Add("Arming Axe", "weapon1h");
            result.Add("Spectral Axe", "weapon1h");
            result.Add("Jasper Axe", "weapon1h");
            result.Add("Tomahawk", "weapon1h");
            result.Add("Wrist Chopper", "weapon1h");
            result.Add("War Axe", "weapon1h");
            result.Add("Chest Splitter", "weapon1h");
            result.Add("Ceremonial Axe", "weapon1h");
            result.Add("Wraith Axe", "weapon1h");
            result.Add("Karui Axe", "weapon1h");
            result.Add("Siege Axe", "weapon1h");
            result.Add("Reaver Axe", "weapon1h");
            result.Add("Vaal Hatchet", "weapon1h");
            result.Add("Royal Axe", "weapon1h");
            result.Add("Infernal Axe", "weapon1h");
            result.Add("Driftwood Club", "weapon1h");
            result.Add("Tribal Club", "weapon1h");
            result.Add("Spiked Club", "weapon1h");
            result.Add("Stone Hammer", "weapon1h");
            result.Add("War Hammer", "weapon1h");
            result.Add("Bladed Mace", "weapon1h");
            result.Add("Ceremonial Mace", "weapon1h");
            result.Add("Dream Mace", "weapon1h");
            result.Add("Petrified Club", "weapon1h");
            result.Add("Barbed Club", "weapon1h");
            result.Add("Rock Breaker", "weapon1h");
            result.Add("Battle Hammer", "weapon1h");
            result.Add("Flanged Mace", "weapon1h");
            result.Add("Ornate Mace", "weapon1h");
            result.Add("Phantom Mace", "weapon1h");
            result.Add("Ancestral Club", "weapon1h");
            result.Add("Tenderizer", "weapon1h");
            result.Add("Gavel", "weapon1h");
            result.Add("Legion Hammer", "weapon1h");
            result.Add("Pernarch", "weapon1h");
            result.Add("Auric Mace", "weapon1h");
            result.Add("Nightmare Mace", "weapon1h");
            result.Add("Rusted Sword", "weapon1h");
            result.Add("Copper Sword", "weapon1h");
            result.Add("Sabre", "weapon1h");
            result.Add("Broad Sword", "weapon1h");
            result.Add("War Sword", "weapon1h");
            result.Add("Ancient Sword", "weapon1h");
            result.Add("Elegant Sword", "weapon1h");
            result.Add("Dusk Blade", "weapon1h");
            result.Add("Variscite Blade", "weapon1h");
            result.Add("Cutlass", "weapon1h");
            result.Add("Baselard", "weapon1h");
            result.Add("Battle Sword", "weapon1h");
            result.Add("Elder Sword", "weapon1h");
            result.Add("Graceful Sword", "weapon1h");
            result.Add("Twilight Blade", "weapon1h");
            result.Add("Gemstone Sword", "weapon1h");
            result.Add("Corsair Sword", "weapon1h");
            result.Add("Gladius", "weapon1h");
            result.Add("Legion Sword", "weapon1h");
            result.Add("Vaal Blade", "weapon1h");
            result.Add("Eternal Sword", "weapon1h");
            result.Add("Midnight Blade", "weapon1h");
            result.Add("Driftwood Sceptre", "weapon1h");
            result.Add("Darkwood Sceptre", "weapon1h");
            result.Add("Bronze Sceptre", "weapon1h");
            result.Add("Quartz Sceptre", "weapon1h");
            result.Add("Iron Sceptre", "weapon1h");
            result.Add("Ochre Sceptre", "weapon1h");
            result.Add("Ritual Sceptre", "weapon1h");
            result.Add("Shadow Sceptre", "weapon1h");
            result.Add("Grinning Fetish", "weapon1h");
            result.Add("Sekhem", "weapon1h");
            result.Add("Crystal Sceptre", "weapon1h");
            result.Add("Lead Sceptre", "weapon1h");
            result.Add("Blood Sceptre", "weapon1h");
            result.Add("Royal Sceptre", "weapon1h");
            result.Add("Abyssal Sceptre", "weapon1h");
            result.Add("Karui Sceptre", "weapon1h");
            result.Add("Tyrant's Sekhem", "weapon1h");
            result.Add("Opal Sceptre", "weapon1h");
            result.Add("Platinum Sceptre", "weapon1h");
            result.Add("Carnal Sceptre", "weapon1h");
            result.Add("Vaal Sceptre", "weapon1h");
            result.Add("Void Sceptre", "weapon1h");
            result.Add("Rusted Spike", "weapon1h");
            result.Add("Whalebone Rapier", "weapon1h");
            result.Add("Battered Foil", "weapon1h");
            result.Add("Basket Rapier", "weapon1h");
            result.Add("Jagged Foil", "weapon1h");
            result.Add("Antique Rapier", "weapon1h");
            result.Add("Elegant Foil", "weapon1h");
            result.Add("Thorn Rapier", "weapon1h");
            result.Add("Wyrmbone Rapier", "weapon1h");
            result.Add("Burnished Foil", "weapon1h");
            result.Add("Estoc", "weapon1h");
            result.Add("Serrated Foil", "weapon1h");
            result.Add("Primeval Rapier", "weapon1h");
            result.Add("Fancy Foil", "weapon1h");
            result.Add("Apex Rapier", "weapon1h");
            result.Add("Dragonbone Rapier", "weapon1h");
            result.Add("Tempered Foil", "weapon1h");
            result.Add("Pecoraro", "weapon1h");
            result.Add("Spiraled Foil", "weapon1h");
            result.Add("Vaal Rapier", "weapon1h");
            result.Add("Jeweled Foil", "weapon1h");
            result.Add("Harpy Rapier", "weapon1h");
            result.Add("Driftwood Wand", "weapon1h");
            result.Add("Goat's Horn", "weapon1h");
            result.Add("Carved Wand", "weapon1h");
            result.Add("Quartz Wand", "weapon1h");
            result.Add("Spiraled Wand", "weapon1h");
            result.Add("Sage Wand", "weapon1h");
            result.Add("Faun's Horn", "weapon1h");
            result.Add("Engraved Wand", "weapon1h");
            result.Add("Crystal Wand", "weapon1h");
            result.Add("Serpent Wand", "weapon1h");
            result.Add("Omen Wand", "weapon1h");
            result.Add("Demon's Horn", "weapon1h");
            result.Add("Imbued Wand", "weapon1h");
            result.Add("Opal Wand", "weapon1h");
            result.Add("Tornado Wand", "weapon1h");
            result.Add("Prophecy Wand", "weapon1h");
            result.Add("Plate Vest", "chest");
            result.Add("Banded Vest", "chest");
            result.Add("Leather Armour", "chest");
            result.Add("Robe", "chest");
            result.Add("Chestplate", "chest");
            result.Add("Ringmail Vest", "chest");
            result.Add("Quilted Leather", "chest");
            result.Add("Scale Cuirass", "chest");
            result.Add("Strapped Leathers", "chest");
            result.Add("Brass Plate", "chest");
            result.Add("Arcanist Vest", "chest");
            result.Add("Hardened Chainmail", "chest");
            result.Add("Leather Tunic", "chest");
            result.Add("Toughened Leather", "chest");
            result.Add("Banded Armour", "chest");
            result.Add("Mammoth Plate", "chest");
            result.Add("Ringmail", "chest");
            result.Add("Caster Robe", "chest");
            result.Add("Quilted Armour", "chest");
            result.Add("Scale Hauberk", "chest");
            result.Add("Leather Jerkin", "chest");
            result.Add("Arcanist Armor", "chest");
            result.Add("Plated Chainmail", "chest");
            result.Add("Sunplate", "chest");
            result.Add("Commander Leather", "chest");
            result.Add("Duelist Cuirass", "chest");
            result.Add("Heavy Strapped Leathers", "chest");
            result.Add("Arena Plate", "chest");
            result.Add("Diplomatic Robe", "chest");
            result.Add("Holy Cloth", "chest");
            result.Add("Ribcage", "chest");
            result.Add("Plated Vest", "chest");
            result.Add("Gladiator Hauberk", "chest");
            result.Add("Inquisitor Armour", "chest");
            result.Add("Gladiator Armour", "chest");
            result.Add("Arcanist Vestment", "chest");
            result.Add("Full Ringmail", "chest");
            result.Add("Bone Armour", "chest");
            result.Add("Imperial Scales", "chest");
            result.Add("Full Strapped Leathers", "chest");
            result.Add("Imperial Plate", "chest");
            result.Add("Arcane Robes", "chest");
            result.Add("Heavy Chainmail", "chest");
            result.Add("Imperial Tunic", "chest");
            result.Add("Reinforced Leather Armour", "chest");
            result.Add("Demonguard Hauberk", "chest");
            result.Add("Rhino Plate", "chest");
            result.Add("Golden Plate", "chest");
            result.Add("Powerweaver Shroud", "chest");
            result.Add("Red Spiderhide", "chest");
            result.Add("Spined Armour", "chest");
            result.Add("Studded Vest", "chest");
            result.Add("Silken Robe", "chest");
            result.Add("Armadillo Carapace", "chest");
            result.Add("Ringmail Jacket", "chest");
            result.Add("Imposing Tunic", "chest");
            result.Add("Plated Tunic", "chest");
            result.Add("Hardened Leather", "chest");
            result.Add("Armadillo Skin Jacket", "chest");
            result.Add("Bladed Armour", "chest");
            result.Add("Stately Vest", "chest");
            result.Add("Razor Chainmail", "chest");
            result.Add("Ancient Shroud", "chest");
            result.Add("Belted Pixane", "chest");
            result.Add("Lamellar Armour", "chest");
            result.Add("Lithe Tunic", "chest");
            result.Add("Regal Plate", "chest");
            result.Add("Ancient Carapace", "chest");
            result.Add("Regal Tunic", "chest");
            result.Add("Rock Shell", "chest");
            result.Add("Grand Inquisitor Armour", "chest");
            result.Add("Majestic Plate", "chest");
            result.Add("Grand Robes", "chest");
            result.Add("Moonplate", "chest");
            result.Add("Woolen Tunic", "chest");
            result.Add("Woven Behterets", "chest");
            result.Add("Weathered Doublet", "chest");
            result.Add("Disc Armour", "chest");
            result.Add("Jagged Plate", "chest");
            result.Add("Withered Shroud", "chest");
            result.Add("Wizened Robes", "chest");
            result.Add("Splinted Armour", "chest");
            result.Add("Scaly Hauberk", "chest");
            result.Add("Stealth Tunic", "chest");
            result.Add("Weathered Vest", "chest");
            result.Add("Hardened Carapace", "chest");
            result.Add("Plated Robe", "chest");
            result.Add("Skeletal Plate", "chest");
            result.Add("Spined Jerkin", "chest");
            result.Add("Painted Tunic", "chest");
            result.Add("Banded Behterets", "chest");
            result.Add("Studded Battleplate", "chest");
            result.Add("Ringmail Coat", "chest");
            result.Add("Skeletal Cage", "chest");
            result.Add("Full Skeletal Armour", "chest");
            result.Add("Mirror Armour", "chest");
            result.Add("Venerable Carapace", "chest");
            result.Add("Chaos Plate", "chest");
            result.Add("Saintly Robes", "chest");
            result.Add("Brigandine", "chest");
            result.Add("Iron Greaves", "feet");
            result.Add("Wool Boots", "feet");
            result.Add("Chainmail Boots", "feet");
            result.Add("Wrapped Boots", "feet");
            result.Add("Leatherscale Boots", "feet");
            result.Add("Rawhide Boots", "feet");
            result.Add("Velvet Boots", "feet");
            result.Add("Plated Greaves", "feet");
            result.Add("Deerskin Boots", "feet");
            result.Add("Ringmail Boots", "feet");
            result.Add("Strapped Boots", "feet");
            result.Add("Ironscale Boots", "feet");
            result.Add("Silk Boots", "feet");
            result.Add("Nubuck Boots", "feet");
            result.Add("Ancient Greaves", "feet");
            result.Add("Clasped Boots", "feet");
            result.Add("Zealot Boots", "feet");
            result.Add("Platescale Boots", "feet");
            result.Add("Embroidered Boots", "feet");
            result.Add("Regal Greaves", "feet");
            result.Add("Slink Boots", "feet");
            result.Add("Shackled Boots", "feet");
            result.Add("Destroyer Greaves", "feet");
            result.Add("Swiftsteel Treads", "feet");
            result.Add("Caster Boots", "feet");
            result.Add("Snakeskin Treads", "feet");
            result.Add("Champion Treads", "feet");
            result.Add("Graveyard Treads", "feet");
            result.Add("Iron Gauntlets", "hands");
            result.Add("Rawhide Gloves", "hands");
            result.Add("Wool Gloves", "hands");
            result.Add("Ironscale Gloves", "hands");
            result.Add("Wrapped Gloves", "hands");
            result.Add("Chainmail Gloves", "hands");
            result.Add("Deerskin Gloves", "hands");
            result.Add("Plated Gauntlets", "hands");
            result.Add("Velvet Gloves", "hands");
            result.Add("Bronzescale Gloves", "hands");
            result.Add("Strapped Gloves", "hands");
            result.Add("Ringmail Gloves", "hands");
            result.Add("Nubuck Gloves", "hands");
            result.Add("Ancient Gauntlets", "hands");
            result.Add("Silk Gloves", "hands");
            result.Add("Platescale Gloves", "hands");
            result.Add("Clasped Gloves", "hands");
            result.Add("Slink Gloves", "hands");
            result.Add("Zealot Gloves", "hands");
            result.Add("Regal Gauntlets", "hands");
            result.Add("Embroided Gloves", "hands");
            result.Add("Riveted Gauntlets", "hands");
            result.Add("Destroyer Gloves", "hands");
            result.Add("Moonlight Gloves", "hands");
            result.Add("Moire Handshrouds", "hands");
            result.Add("Shagreen Vambraces", "hands");
            result.Add("Jaconet Grips", "hands");
            result.Add("Rusted Casque", "head");
            result.Add("Felt Cap", "head");
            result.Add("Rusted Helmet", "head");
            result.Add("Vine Circlet", "head");
            result.Add("Rusted Mask", "head");
            result.Add("Rusted Chain Cap", "head");
            result.Add("Copper Circlet", "head");
            result.Add("Tribal Mask", "head");
            result.Add("Leather Cap", "head");
            result.Add("Executioner Casque", "head");
            result.Add("Chain Cap", "head");
            result.Add("Flanged Helmet", "head");
            result.Add("Tribal Circlet", "head");
            result.Add("Copper Mask", "head");
            result.Add("Gladiator Casque", "head");
            result.Add("Leather Hood", "head");
            result.Add("Crusader Helmet", "head");
            result.Add("Ribbed Helmet", "head");
            result.Add("Gemmed Circlet", "head");
            result.Add("Crusader Casque", "head");
            result.Add("Studded Hood", "head");
            result.Add("Gilded Chain Helmet", "head");
            result.Add("Ritual Mask", "head");
            result.Add("Gilded Helmet", "head");
            result.Add("Gilded Circlet", "head");
            result.Add("Imperial Casque", "head");
            result.Add("Decadent Mask", "head");
            result.Add("Harpy Crown", "head");
            result.Add("Cadaver Mask", "head");
            result.Add("Mage Miter", "head");
            result.Add("Destroyer Crown", "head");
            result.Add("Brawler Helm", "head");
            result.Add("Teutonic Helm", "head");
            result.Add("Plain Buckler", "shield");
            result.Add("Salvaged Wall Shield", "shield");
            result.Add("Tribal Armguard", "shield");
            result.Add("Tribal Kite Shield", "shield");
            result.Add("Tribal Buckler", "shield");
            result.Add("Salvaged Shield", "shield");
            result.Add("Tribal Wall Shield", "shield");
            result.Add("Bone Focus", "shield");
            result.Add("Rustic Armguard", "shield");
            result.Add("Bronze Buckler", "shield");
            result.Add("Reinforced Kite Shield", "shield");
            result.Add("Etched Shield", "shield");
            result.Add("Iron Wall Shield", "shield");
            result.Add("Tribal Focus", "shield");
            result.Add("Reinforced Buckler", "shield");
            result.Add("Crusaders Kite Shield", "shield");
            result.Add("Imperial Shield", "shield");
            result.Add("Leather Armguard", "shield");
            result.Add("Steel Buckler", "shield");
            result.Add("Vine Focus", "shield");
            result.Add("Etched Wall Shield", "shield");
            result.Add("Bladed Shield", "shield");
            result.Add("Engraved Buckler", "shield");
            result.Add("Steel Kite Shield", "shield");
            result.Add("Steel Armguard", "shield");
            result.Add("Gilded Buckler", "shield");
            result.Add("Ornate Focus", "shield");
            result.Add("Ornate Wall Shield", "shield");
            result.Add("Eternal Focus", "shield");
            result.Add("Immortal Armguard", "shield");
            result.Add("Templar Shield", "shield");
            result.Add("Cavalier Shield", "shield");
            result.Add("Reaver Shield", "shield");
            result.Add("Hunting Shield", "shield");
            result.Add("Portrait Shield", "shield");
            result.Add("Sigil Kite Shield", "shield");
            result.Add("Ornate Armguard", "shield");

            return result;
        }
    }
}
